### Setup Environment:

In [3]:
from src.get_dataset import get_dataset

### Get the dataset

**Note:** Set download to `True` to download the dataset from pyhsionet into `data/`

it will generate a structure like:

* data/
    * lables.csv
    * images/
        * image_1.jpg
        * image_2.jpg
        * image_3.jpg
        
        ...
        
        * image_n.jpg

In [ ]:
# Constants:
DATASET = 'data/'
DOWNLOAD = False

In [5]:
get_dataset("data/", download=DOWNLOAD)

loading csv file in data//labels.csv
Number of Rows: 16266
Number of Columns: 34
Column Names: image_id, patient_id, camera, patient_age, comorbidities, diabetes_time_y, insuline, patient_sex, exam_eye, diabetes, nationality, optic_disc, vessels, macula, DR_SDRG, DR_ICDR, focus, iluminaton, image_field, artifacts, diabetic_retinopathy, macular_edema, scar, nevus, amd, vascular_occlusion, hypertensive_retinopathy, drusens, hemorrhage, retinal_detachment, myopic_fundus, increased_cup_disc, other, quality

Description:
         patient_id   patient_age   patient_sex      exam_eye       vessels  \
count  16266.000000  10821.000000  16266.000000  16266.000000  16266.000000
mean    4275.474302     57.655947      1.617976      1.498647      1.049613
std     2463.584452     18.260156      0.485897      0.500014      0.217150
min        1.000000      5.000000      1.000000      1.000000      1.000000
25%     2158.250000     47.000000      1.000000      1.000000      1.000000
50%     4270.000000     61.000000      2.000000      1.000000      1.000000
75%     6420.750000     71.000000      2.000000      2.000000      1.000000
max     8524.000000     97.000000      2.000000      2.000000      2.000000

             macula       DR_SDRG       DR_ICDR         focus    iluminaton  \
count  16266.000000  16266.000000  16266.000000  16266.000000  16266.000000
mean       1.288024      0.180868      0.180007      1.033321      1.005164
std        0.452856      0.750198      0.739261      0.179479      0.071678
min        1.000000      0.000000      0.000000      1.000000      1.000000
25%        1.000000      0.000000      0.000000      1.000000      1.000000
50%        1.000000      0.000000      0.000000      1.000000      1.000000
75%        2.000000      0.000000      0.000000      1.000000      1.000000
max        2.000000      4.000000      4.000000      2.000000      2.000000

       ...         nevus           amd  vascular_occlusion  \
count  ...  16266.000000  16266.000000        16266.000000
mean   ...      0.008238      0.022501            0.006332
std    ...      0.090392      0.148310            0.079325
min    ...      0.000000      0.000000            0.000000
25%    ...      0.000000      0.000000            0.000000
50%    ...      0.000000      0.000000            0.000000
75%    ...      0.000000      0.000000            0.000000
max    ...      1.000000      1.000000            1.000000

       hypertensive_retinopathy       drusens    hemorrhage  \
count              16266.000000  16266.000000  16266.000000
mean                   0.017398      0.172569      0.005902
std                    0.130754      0.377885      0.076599
min                    0.000000      0.000000      0.000000
25%                    0.000000      0.000000      0.000000
50%                    0.000000      0.000000      0.000000
75%                    0.000000      0.000000      0.000000
max                    1.000000      1.000000      1.000000

       retinal_detachment  myopic_fundus  increased_cup_disc         other
count        16266.000000   16266.000000        16266.000000  16266.000000
mean             0.000430       0.016476            0.196852      0.046600
std              0.020741       0.127301            0.397632      0.210788
min              0.000000       0.000000            0.000000      0.000000
25%              0.000000       0.000000            0.000000      0.000000
50%              0.000000       0.000000            0.000000      0.000000
75%              0.000000       0.000000            0.000000      0.000000
max              1.000000       1.000000            1.000000      1.000000

[8 rows x 25 columns]

,image_id,patient_id,camera,patient_age,comorbidities,diabetes_time_y,insuline,patient_sex,exam_eye,diabetes,...,amd,vascular_occlusion,hypertensive_retinopathy,drusens,hemorrhage,retinal_detachment,myopic_fundus,increased_cup_disc,other,quality
0,img00001,1,Canon CR,48.0,diabetes1,12,yes,1,1,yes,...,0,0,0,0,0,0,0,1,0,Adequate
1,img00002,1,Canon CR,48.0,diabetes1,12,yes,1,2,yes,...,0,0,0,0,0,0,0,1,0,Adequate
2,img00003,2,Canon CR,18.0,diabetes1,7,yes,2,1,yes,...,0,0,0,0,0,0,0,0,0,Adequate
3,img00004,2,Canon CR,18.0,diabetes1,7,yes,2,2,yes,...,0,0,0,0,0,0,0,0,0,Adequate
4,img00005,3,Canon CR,22.0,diabetes1,11,yes,1,1,yes,...,0,0,0,0,0,0,0,0,0,Adequate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16261,img16262,8522,Canon CR,33.0,diabetes1,14,yes,1,2,yes,...,0,0,0,0,0,0,0,1,0,Adequate
16262,img16263,8523,Canon CR,19.0,diabetes1,4,yes,1,1,yes,...,0,0,0,0,0,0,0,0,0,Adequate
16263,img16264,8523,Canon CR,19.0,diabetes1,4,yes,1,2,yes,...,0,0,0,0,0,0,0,0,0,Adequate
16264,img16265,8524,Canon CR,20.0,diabetes1,NaN,yes,1,1,yes,...,0,0,0,0,0,0,0,1,0,Adequate
16265,img16266,8524,Canon CR,20.0,diabetes1,NaN,yes,1,2,yes,...,0,0,0,0,0,0,0,0,0,Adequate